<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>25ffc5fa-e330-485d-8b0f-edf31d32a7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.text-third-foreground.shadow-xl.bg-third.whitespace-nowrap.rounded-full.text-sm[data-slot=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-third-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-third ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (@data-slot = 'button')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29d56362-e7a8-4fe2-8b53-f18dc05bbc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbf969e0-1b2e-423c-ab8c-0a97c71411a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center gap-2 whitespace-nowrap text-sm disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive bg-third hover:bg-third/90 text-third-foreground rounded-full font-bold shadow-xl shadow-third/20 active:scale-95 transition-all h-11 px-6 py-2.5 has-[>svg]:px-5</value>
      <webElementGuid>d717673c-88f1-4006-9ee7-95071be7eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>56a62cb0-8b94-4fa5-a496-2588b6417a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9e604f6aa66ae59e0e25232a5188de67</value>
      <webElementGuid>c41367d8-7759-4d38-89dc-baccd3ce0c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-third-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-third ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (@data-slot = 'button')]</value>
      <webElementGuid>23b3ff76-9db3-4352-8132-9beb799aa75d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-third-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-third ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (@data-slot = 'button')]</value>
      <webElementGuid>04a1b275-df61-4143-bdb1-6b04f6c788e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>1fa9da74-3092-4b4c-9058-65bbc56f00e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
